### ISSUE TITLE
Interaction error handling may throw.

### ISSUE THREAD

**Issue by moonstar-x** [greencoast-studios/discord.js-extended#58]
#### :bug: Describe the Bug

If inside a command the run command throws, the exception is caught by the CommandDispatcher. However, the catch block of the handleInteraction function may also throw when trying to reply to an interaction because it may have timed out or because it may have been deferred. This crashes the bot because obviously that isn't handled properly.

#### :pencil2: Steps to Reproduce

- Have a command that defers a reply and throws inside of its run command.

#### :scroll: Log

``` text
(10:58:51 AM) - [ERROR] - TypeError: Cannot read property 'name' of undefined at /Users/moonstar/Desktop/github_moonstar-x/discord-tts-bot/src/utils/mentions.js:18:77 at String.replace (<anonymous>) at cleanEmojis (/Users/moonstar/Desktop/github_moonstar-x/discord-tts-bot/src/utils/mentions.js:18:18) at cleanMessage (/Users/moonstar/Desktop/github_moonstar-x/discord-tts-bot/src/utils/mentions.js:27:11) at SayCommand.run (/Users/moonstar/Desktop/github_moonstar-x/discord-tts-bot/src/commands/all-tts/SayCommand.js:40:21)
```

**Comment by moonstar-x** [comment]
Added in #60.
